# Generated by Django 4.2.9 on 2025-07-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoFeederData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_start_time', models.CharField(max_length=255)),
                ('auto_end_time', models.CharField(max_length=255)),
                ('auto_feed_rate', models.CharField(max_length=255)),
                ('auto_sprinkle_rate', models.CharField(max_length=255)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManualFeederData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_start_time', models.CharField(max_length=255)),
                ('manual_end_time', models.CharField(max_length=255)),
                ('manual_feed_rate', models.CharField(max_length=255)),
                ('manual_sprinkle_rate', models.CharField(max_length=255)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
