# Generated by Django 5.2.1 on 2025-06-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeederData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=255)),
                ('feed_rate', models.CharField(max_length=255)),
                ('sprinkle_rate', models.CharField(max_length=255)),
            ],
        ),
    ]
