# Generated by Django 5.2.1 on 2025-06-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feederdata',
            name='end_time',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
