# Generated by Django 4.2.9 on 2025-07-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alert_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert_message_manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert', models.CharField(max_length=255)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Alert_message',
            new_name='Alert_message_auto',
        ),
    ]
