# Generated by Django 5.2.1 on 2025-06-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_feederdata_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoFeederData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_start_time', models.CharField(max_length=255)),
                ('auto_end_time', models.CharField(max_length=255)),
                ('auto_feed_rate', models.CharField(max_length=255)),
                ('auto_sprinkle_rate', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ManualFeederData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_start_time', models.CharField(max_length=255)),
                ('manual_end_time', models.CharField(max_length=255)),
                ('manual_feed_rate', models.CharField(max_length=255)),
                ('manual_sprinkle_rate', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='FeederData',
        ),
    ]
