# Generated by Django 4.2.9 on 2025-07-16 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alert_message_manual_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alert_message_auto',
            new_name='Alert_message',
        ),
        migrations.DeleteModel(
            name='Alert_message_manual',
        ),
    ]
