# Generated by Django 4.2.9 on 2025-07-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_alert_message_auto_alert_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=30)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('Mob', models.BigIntegerField(unique=True)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
