# Generated by Django 4.2.9 on 2025-07-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='Device_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
