# Generated by Django 5.2.7 on 2025-10-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_myuser_device_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeederSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_value', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
