# Generated by Django 5.2.7 on 2025-10-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_feedersetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedersetting',
            name='percentage',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='feedersetting',
            name='point_value',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
