# Generated by Django 5.2.7 on 2025-10-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_feedersetting_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedersetting',
            name='percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='feedersetting',
            name='point_value',
            field=models.IntegerField(default=0),
        ),
    ]
